/* eslint-disable */
export default {
  // Course related errors
  COURSE_NOT_FOUND: 'COURSE_NOT_FOUND',
  COURSE_EVENTS_NOT_FOUND: 'COURSE_EVENTS_NOT_FOUND',
  COURSE_EVENTS_NOT_PARSED: 'COURSE_EVENTS_NOT_PARSED',
  COURSE_EVENTS_LOCATION_NOT_FOUND: 'COURSE_EVENTS_LOCATION_NOT_FOUND',
  COURSE_HAS_NO_TEACHING: 'COURSE_HAS_NO_TEACHING',
  INVALID_COURSE_CODE: 'INVALID_COURSE_CODE',

  // User related errors
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_NOT_ADDED: 'USER_NOT_ADDED',
  USER_NOT_DELETED: 'USER_NOT_DELETED',
  USER_COURSE_NOT_REMOVED: 'USER_COURSE_NOT_REMOVED',
  PASSWORD_NO_MATCH: 'PASSWORD_NO_MATCH',

  // Other
  INVALID_DATA: 'INVALID_DATA',
};
/* eslint-enable */
