/* eslint-disable */
export default {
  ERROR_COURSE_NOT_FOUND: 'ERROR_COURSE_NOT_FOUND',
  ERROR_COURSE_EVENTS_NOT_FOUND: 'ERROR_COURSE_EVENTS_NOT_FOUND',
  ERROR_COURSE_EVENTS_NOT_PARSED: 'ERROR_COURSE_EVENTS_NOT_PARSED',
  ERROR_COURSE_EVENTS_LOCATION_NOT_FOUND: 'ERROR_COURSE_EVENTS_LOCATION_NOT_FOUND',
  ERROR_COURSE_HAS_NO_TEACHING: 'ERROR_COURSE_HAS_NO_TEACHING',
};
/* eslint-enable */
