---
- name: restart mongod
  become: 'yes'
  become_method: 'sudo'
  service: name=mongod state=restarted

- name: selenium_started
  become: 'yes'
  become_method: 'sudo'
  service: name=selenium_standalone state=started enabled=yes

- name: selenium_reload
  become: 'yes'
  become_method: 'sudo'
  service: name=selenium_standalone state=reloaded
