- hosts: all
  become: 'yes'
  become_method: 'sudo'
  become_user: 'lukkari'
  tasks:
    - name: Update code from git
      tags: ['new_release']
      git:
        repo: git@github.com:MSP-project/lukkari-api.git
        dest: /var/www/lukkari-api/
        update: yes
        force: yes
        version: master
        accept_hostkey: yes
        key_file: /home/lukkari/.ssh/id_rsa

    - name: Install global nodejs packages
      npm:
        name: "{{ item }}"
        global: yes
      with_items:
        - pm2


    # ---------------- Build API ----------------
    - name: Install initial server dependencies with npm
      tags: ['new_release']
      npm:
        path: /var/www/lukkari-api

    - name: Build production version of api code
      tags: ['new_release']
      command: npm run build:prod
      args:
        chdir: /var/www/lukkari-api/

    - name: Copy index.js to build directory
      tags: ['new_release']
      command: cp /var/www/lukkari-api/index.production.js /var/www/_build/index.js

    - name: Copy prod .env file to _build
      tags: ['new_release']
      command: cp /var/www/lukkari-api/.env-production /var/www/_build/.env

    - name: Copy package.json to build directory
      tags: ['new_release']
      command: cp /var/www/lukkari-api/package.json /var/www/_build/

    - name: Install build dependencies with npm
      tags: ['new_release']
      npm: path=/var/www/_build production=yes

    - name: Install pm2 startup script
      command: pm2 startup debian -u lukkari

    - name: Delete existing pm2 node apps
      tags: ['new_release']
      command: pm2 delete all
      ignore_errors: yes

    - name: Start lukkari node app with pm2
      tags: ['new_release']
      command: pm2 start -f /var/www/_build/index.js --name="api"
    # ---------------- /Build api ----------------
